version: '2'
services:

  hub:
    image: sunx2ych/alpine-selenium-hub:2.53.0
    ports:
      - "4444:4444"

  firefox:
    image: sunx2ych/alpine-selenium-node-firefox:2.53.0
    links:
      - hub
